@startuml door_controller_mcu

node door_controller_mcu {
    package Application {
        component DoorLogic
        component Door_FSM
        component DoorRelease_FSM
        component StopRequest_FSM

        StopRequest_FSM --> DoorLogic : STOP_REQUEST_EVENT
        DoorLogic ==> StopRequest_FSM : SET_STOP_REQUEST_COMMAND [!door_release_active_state || !vehicle_stopped_state]
        DoorLogic ==> Door_FSM : OPEN_DOORS_COMMAND [!door_release_active_state && vehicle_stopped_state && STOP_REQUEST_EVENT]


    }


    package Hardware {
        component StopRequest_Button
        component DoorRelease_Button
        component StopRequest_LED
        component DoorRelease_LED
    }

    StopRequest_Button --> StopRequest_FSM : STOP_REQUEST_EVENT_BUTTON_PRESSED







}



@enduml