@startuml door_release_fsm


state DoorRelease_FSM {
    [*] --> STATE_DOOR_RELEASE_INACTIVE
    state STATE_DOOR_RELEASE_INACTIVE
    state STATE_DOOR_RELEASE_ACTIVE

    STATE_DOOR_RELEASE_INACTIVE: output state_door_release = STATE_DOOR_RELEASE_INACTIVE
    STATE_DOOR_RELEASE_INACTIVE: is_door_release_led_on = false

    STATE_DOOR_RELEASE_ACTIVE: output state_door_release = STATE_DOOR_RELEASE_ACTIVE
    STATE_DOOR_RELEASE_ACTIVE: is_door_release_led_on = true


    STATE_DOOR_RELEASE_INACTIVE --> STATE_DOOR_RELEASE_ACTIVE : CMD_DOOR_RELEASE_ACTIVATE
    STATE_DOOR_RELEASE_ACTIVE --> STATE_DOOR_RELEASE_INACTIVE : CMD_DOOR_RELEASE_DEACTIVATE
}

@enduml