@startuml fallback_door_release_fsm

state FALLBACK_DOOR_RELEASE_FSM {
    [*] --> STATE_FALLBACK_DOOR_RELEASE_INACTIVE
    state STATE_FALLBACK_DOOR_RELEASE_INACTIVE
    state STATE_FALLBACK_DOOR_RELEASE_ACTIVE

    STATE_FALLBACK_DOOR_RELEASE_INACTIVE: output state_fallback_door_release = STATE_FALLBACK_DOOR_RELEASE_INACTIVE
    STATE_FALLBACK_DOOR_RELEASE_INACTIVE: fallback_door_release_led_on = false


    STATE_FALLBACK_DOOR_RELEASE_ACTIVE: output state_fallback_door_release = STATE_FALLBACK_DOOR_RELEASE_ACTIVE
    STATE_FALLBACK_DOOR_RELEASE_ACTIVE: fallback_door_release_led_on = true

    STATE_FALLBACK_DOOR_RELEASE_INACTIVE --> STATE_FALLBACK_DOOR_RELEASE_ACTIVE : CMD_FALLBACK_DOOR_RELEASE_ACTIVATE
    STATE_FALLBACK_DOOR_RELEASE_ACTIVE --> STATE_FALLBACK_DOOR_RELEASE_INACTIVE : CMD_FALLBACK_DOOR_RELEASE_DEACTIVATE

}


@enduml