@startuml node_door_controller

' Events shall not be the sole source of information for for safety-critical decisions/actions
' Safety-critical decisions shall rely on periodically transmitted system states
' and, in professional safety systems, additional supervision mechanisms (e.g. Türüberwachung)

legend top
Event:
    instanteneous notification

Command:
    request for an action

State:
    periodically transmitted system condition


endlegend

component DoorLogic

component StopRequestState
component DoorReleaseState
component DoorState


DoorLogic --> StopRequestState : STOP_REQUEST_RESET_COMMAND

DoorState --> DoorLogic : DOOR_OPENED_EVENT

StopRequestState --> DoorLogic : STOP_REQUEST_SET_EVENT




@enduml