@startuml stop_request_fsm




state StopRequestFSM {
    [*] --> STATE_STOP_REQUEST_RESET
    state STATE_STOP_REQUEST_RESET
    state STATE_STOP_REQUEST_SET

    STATE_STOP_REQUEST_RESET: ouput state_stop_request = STATE_STOP_REQUEST_RESET 
    STATE_STOP_REQUEST_RESET: signal light off

    STATE_STOP_REQUEST_SET: output state_stop_request = STATE_STOP_REQUEST_SET
    STATE_STOP_REQUEST_SET: signal light on


    STATE_STOP_REQUEST_RESET --> STATE_STOP_REQUEST_SET : CMD_STOP_REQUEST_SET
    STATE_STOP_REQUEST_SET --> STATE_STOP_REQUEST_RESET : CMD_STOP_REQUEST_RESET
}


@enduml