@startuml state-machine_door-safety

legend left
s. = system
d. = driver
p. = passenger

Stopped_ImmobilizerActive is a safe state as long as the 
door release is only pressed inside the perimeters of a station
endlegend


state SafeState {
    state Stopped {
        [*] --> Stopped_Idle

        state Stopped_Idle
        state Stopped_ImmobilizerActive {
            state Stopped_DoorReleased_StationDetected
            state Stopped_DoorReleased_NotStationDetected
            state Stopped_FallbackDoorReleased
            state Stopped_NotDoorReleased_DoorOpen
            state Stopped_EmergencyExitUsed
        }
    }

    state Moving
}


state SpecialState {
    state ExceptionState {
        state DoorMalfunction
    }

    state ErrorState {
        state Moving_DoorOpen
    }
}


ExceptionState: manageable fault condition

ErrorState: safety-critical invalid state requiring immediate intervention

Stopped_ImmobilizerActive: brakes are enforced
Stopped_ImmobilizerActive: s. ignores drive input
Stopped_ImmobilizerActive: s. warns d., when drive input is given

Stopped_Idle: door release inactive
Stopped_Idle: doors are closed
Stopped_Idle: stop may be requested


Stopped_DoorReleased_StationDetected: releasing door resets stop request
Stopped_DoorReleased_StationDetected: stop request opens door
Stopped_DoorReleased_StationDetected: doors close automatically or manually

Stopped_DoorReleased_NotStationDetected: s. blocks door release
Stopped_DoorReleased_NotStationDetected: s. does not open any door
Stopped_DoorReleased_NotStationDetected: s. warns d. - station not detected

Stopped_FallbackDoorReleased: s. ignores station detection
Stopped_FallbackDoorReleased: s. allows opening of doors via stop request
Stopped_FallbackDoorReleased: s. informs d., that fallback is set
Stopped_FallbackDoorReleased: fallback can be used, in case of:
Stopped_FallbackDoorReleased: - technical malfunctions
Stopped_FallbackDoorReleased: - emergencies

Stopped_NotDoorReleased_DoorOpen: d. waiting for doors to close
Stopped_NotDoorReleased_DoorOpen: s. does not open door when stop is requested
Stopped_NotDoorReleased_DoorOpen: s. informs driver when stop is requested


Stopped_EmergencyExitUsed: s. alerts d.
Stopped_EmergencyExitUsed: at least one door open


Moving: doors are closed
Moving: stop may be requested


DoorMalfunction: e.g. doors stay closed even though
DoorMalfunction: - door_release is set
DoorMalfunction: - AND stop is requested
DoorMalfunction: e.g. light barrier defective


Moving_DoorOpen: s. alerts d.
Moving_DoorOpen: s. stops vehicle


Stopped_Idle --> Stopped_DoorReleased_StationDetected : d. sets door release [vehicle stopped, station detected]
Stopped_DoorReleased_StationDetected --> Stopped_Idle : passenger transfer finished [doors closed, then reset door release]

Stopped_Idle --> Stopped_DoorReleased_NotStationDetected : d. sets door release [vehicle stopped, station not detected]
Stopped_DoorReleased_NotStationDetected --> Stopped_Idle : d. resets door release

Stopped_Idle --> Stopped_FallbackDoorReleased : d. sets fallback door release [vehicle stopped]
Stopped_FallbackDoorReleased --> Stopped_Idle : d. resets fallback door release

Stopped_Idle --> Moving : vehicle accelerates
Moving --> Stopped_Idle : vehicle stops

Stopped_DoorReleased_StationDetected --> Stopped_NotDoorReleased_DoorOpen : d. resets door release [not all doors closed]
Stopped_NotDoorReleased_DoorOpen --> Stopped_DoorReleased_StationDetected : d. sets door release [not all doors closed]

Stopped_FallbackDoorReleased --> Stopped_NotDoorReleased_DoorOpen : d. resets fallback door release [not all doors closed]
Stopped_NotDoorReleased_DoorOpen --> Stopped_FallbackDoorReleased : d. sets fallback door release [not all doors closed]

SafeState --> DoorMalfunction : door malfunction reported / s. warns d.
DoorMalfunction --> SafeState : d. resolves malfunction

Stopped_NotDoorReleased_DoorOpen --> Stopped_Idle : all doors closed

Moving --> Moving : d. sets door release / s. blocks request; warns d.


Moving --> Moving_DoorOpen : door opens while moving
Moving_DoorOpen --> Stopped_Idle : Error handled [vehicle stopped AND all doors closed]


@enduml