@startuml state-machine_door-safety

legend left
Stopped_BrakesEnforced is a safe state as long as the 
door release is only pressed inside the perimeters of a station
endlegend


state SafeState {
    [*] --> Stopped_Idle
    state Stopped_Idle
    state Stopped_BrakesEnforced {
        state Stopped_DoorReleased
        state Stopped_EmergencyExitUsed
    }
    state Moving
}

state Exception {
    state Stopped_DoorMalfunction
}

state Error {
    state Moving_DoorOpen
}

Stopped_Idle: door release inactive
Stopped_Idle: doors are closed
Stopped_Idle: stop may be requested


Stopped_DoorReleased: releasing door resets stop request
Stopped_DoorReleased: stop request opens door
Stopped_DoorReleased: doors close automatically or manually

Stopped_EmergencyExitUsed: system alerts driver
Stopped_EmergencyExitUsed: at least one door open

Moving: doors are closed
Moving: stop may be requested


Stopped_DoorMalfunction: doors stay closed even though
Stopped_DoorMalfunction: - door_release is set
Stopped_DoorMalfunction: - AND stop is requested


Moving_DoorOpen: system alerts driver
Moving_DoorOpen: system stops vehicle


Stopped_Idle --> Stopped_DoorReleased : driver sets door release [vehicle stopped]
Stopped_DoorReleased --> Stopped_Idle : passenger transfer finished

Stopped_Idle --> Stopped_EmergencyExitUsed : passenger opened emergency exit
Stopped_EmergencyExitUsed --> Stopped_Idle : driver resets emergency exit

Stopped_Idle --> Moving : vehicle accelerates
Moving --> Stopped_Idle : vehicle stops


Stopped_DoorReleased --> Stopped_EmergencyExitUsed : passenger opened emergency exit
Stopped_EmergencyExitUsed --> Stopped_DoorReleased : driver resets emergency exit

Stopped_DoorReleased --> Stopped_DoorMalfunction : stop request failed / system warns driver
Stopped_DoorMalfunction --> Stopped_DoorReleased : driver resolves malfunction


Moving --> Moving : driver sets door release / system blocks request; warns driver


Moving --> Moving_DoorOpen : door opens while moving
Moving_DoorOpen --> Stopped_Idle : vehicle stopped AND all doors closed


@enduml