@startuml state_machine_tram

legend left
Produced signals:
    DrivingState:
        - vehicle_stopped

    StopRequestState:
        - stop_request_set
    
    DoorReleaseState:
        - door_release_active
    
    FallbackDoorReleaseState:
        - fallback_door_release_active
    
    StationDetectionState:
        - station_detected

    DoorState:
        - doors_closed


Consumed signals:
    DrivingState:
        - doors_closed
        - door_release_active
        - fallback_door_release_active
    
    StopRequestState:
        - doors_closed
        - door_release_active
        - fallback_door_release_active
    
    DoorReleaseState:
        - station_detected
        - vehicle_stopped
    
    FallbackDoorReleaseState:
        - vehicle_stopped
    
    StationDetectionState:
        - none
    
    DoorState:
        - stop_request_set
        - door_release_active
        - fallback_door_release_active
        - internal timer event

endlegend


state DrivingState {
    [*] --> Stopped
    state Stopped
    state Moving {
        [*] --> Accelerating
        state Accelerating
        state Rolling
        state Braking

        Accelerating: traction command applied

        Rolling: traction command idle

        Braking: brake command applied


        Accelerating --> Rolling
        Rolling --> Accelerating
        Rolling --> Braking
        Braking --> Rolling
    }

    Stopped: velocity == 0

    Moving: velocity != 0


    Stopped --> Moving : [doors_closed and !door_release_active and !fallback_door_release_active]
    Moving --> Stopped : [vehicle_stopped]
    
}

--

state StopRequestState {
    [*] --> StopRequest_Reset
    state StopRequest_Reset
    state StopRequest_Set

    StopRequest_Reset: signal light off

    StopRequest_Set: signal light on


    StopRequest_Reset --> StopRequest_Reset : passenger presses stop button [(door_release_active or fallback_door_release_active) and vehicle_stopped] / request immediate door opening
    StopRequest_Reset --> StopRequest_Set : passenger presses stop button / activate acoustic signal
    StopRequest_Set --> StopRequest_Set : passenger presses stop button again
    StopRequest_Set --> StopRequest_Reset : [(door_release_active and station_detected and !doors_closed) or (fallback_door_release_active and !doors_closed)] / request immediate door opening
}

--

state DoorReleaseState {
    [*] --> DoorRelease_Inactive
    state DoorRelease_Inactive
    state DoorRelease_Active

    DoorRelease_Inactive: doors are blocked

    DoorRelease_Active: doors open whenever stop is requested
    DoorRelease_Active: only active inside of station perimeter

    DoorRelease_Inactive --> DoorRelease_Active : door release button is set [vehicle_stopped and station_detected] / doors are released
    DoorRelease_Inactive --> DoorRelease_Inactive : door release button is set [!vehicle_stopped or !station_detected] / block door release, warn driver
    DoorRelease_Active --> DoorRelease_Inactive : door release button is reset / clear warning
}

--

state FallbackDoorReleaseState {
    [*] --> FallbackDoorRelease_Inactive
    state FallbackDoorRelease_Inactive
    state FallbackDoorRelease_Active

    FallbackDoorRelease_Inactive: doors are blocked

    FallbackDoorRelease_Active: doors open whenever stop is requested
    FallbackDoorRelease_Active: can be active outside of station perimeter

    FallbackDoorRelease_Inactive --> FallbackDoorRelease_Active : door release button is set [vehicle_stopped] / doors are released
    FallbackDoorRelease_Inactive --> FallbackDoorRelease_Inactive : door release button is set [!vehicle_stopped] / block fallback door release, warn driver
    FallbackDoorRelease_Active --> FallbackDoorRelease_Inactive : door release button is reset / clear warning


}

--

state StationDetectionState {
    [*] --> No_Station_Detected
    state Station_Detected
    state No_Station_Detected

    Station_Detected: vehicle is inside of station perimeter along its entire length

    No_Station_Detected: vehicle is outside of station perimeter


    No_Station_Detected --> Station_Detected : tram passes signal at entrance of station
    Station_Detected --> No_Station_Detected : tram passes signal at exit of station


}

--

state DoorState {
    [*] --> Doors_Closed
    state Doors_Closed
    /'state Doors_Closing'/
    state Doors_Open
    /'state Doors_Opening'/

    Doors_Closed --> Doors_Open : [(door_release_active or fallback_door_release_active) and stop_request_set] / open door
    Doors_Open --> Doors_Closed : three seconds passed after last valid opening request
}

/'

--

state DoorDiagnosticState {
    [*] --> Doors_Operational
    state Doors_Operational
    state Doors_Malfunction

    Doors_Operational --> Doors_Malfunction : Malfunction detected
    Doors_Malfunction --> Doors_Operational : Malfunction resolved
}

--

state PassengerEmergencyBrakeState {
    [*] --> PEB_Inactive
    state PEB_Inactive
    state PEB_Active
}

--

state PassengerEmergencyDoorReleaseState {
    [*] --> PEDR_Inactive
    state PEDR_Inactive
    state PEDR_Active

}

--

state SpringLoadedBrakeState {
    [*] --> SLB_Active
    state SLB_Active
    state SLB_Activating
    state SLB_Releasing
    state SLB_Released

    SLB_Active --> SLB_Releasing
    SLB_Releasing --> SLB_Released
    SLB_Releasing --> SLB_Activating
    SLB_Activating --> SLB_Active
    SLB_Released --> SLB_Activating

}
'/
@enduml