@startuml fallback_door_release_supervisor_activity

start

:Receive EV_FALLBACK_DOOR_RELEASE_BUTTON_PRESSED;


if (state_fallback_door_release == STATE_FALLBACK_DOOR_RELEASE_ACTIVE) then (true)
    :Emit CMD_FALLBACK_DOOR_RELEASE_DEACTIVATE;


else (false)

    if (state_vehicle_movement == STATE_VEHICLE_STOPPED) then (true) 
        :Emit CMD_FALLBACK_DOOR_RELEASE_ACTIVATE;
    else (false)
        :Reject request;
        :Warn driver;

    endif

endif


stop

@enduml