@startuml traction_command_fsm

state TRACTION_COMMAND_FSM {
    state STATE_TRACTION_COMMAND_IDLE
    state STATE_TRACTION_COMMAND_TRACTION
    state STATE_TRACTION_COMMAND_BRAKE
    state STATE_TRACTION_COMMAND_EMERGENCY_BRAKE
}

@enduml