#ifndef INPUT_TRACTION_CONTROLLER_H
#define INPUT_TRACTION_CONTROLLER_H

#include <stdint.h>

typedef enum {
	INPUT_TRACTION_CONTROLLER_STATUS_ERROR,
	INPUT_TRACTION_CONTROLLER_STATUS_INVALID_INPUT,
	INPUT_TRACTION_CONTROLLER_STATUS_INVALID_ARGUMENT,
	INPUT_TRACTION_CONTROLLER_STATUS_TIME_OUT,
	INPUT_TRACTION_CONTROLLER_STATUS_UNKNOWN,
	INPUT_TRACTION_CONTROLLER_STATUS_OK
} InputTractionControllerStatus_t;


InputTractionControllerStatus_t get_traction_controller_percentage(int8_t *percentage);

#endif
