@startuml door_release_supervisor_activity


start

:Receive EV_DOOR_RELEASE_BUTTON_PRESSED;

if (state_door_release == ACTIVE) then (true)
    :Emit cmd_door_release_deactivate;

else (false) 
    if (state_vehicle_movement == STOPPED
        && state_vehicle_movement_info == VALID
        && state_station_detection == DETECTED
        && state_station_detection_info == VALID) then (true)
        :Emit cmd_door_release_activate;

    else (false)
        :Reject request;
        :Warn driver;

    endif

endif

stop



@enduml