@startuml door_supervisor_activity

start

:Receive RQST_DOORS_OPEN;

if (state_door_opening_permission == GRANTED) then (true)
    if (state_doors == CLOSED) then (true)
        :Emit cmd_doors_open;
        :Start door_timer;

    else (false)
        :Restart door_timer;

    endif

else (false)
    :Emit warning, that doors are not allowed to open;


endif




stop

start

:Cyclic check_door_timer;

'Note: there would be additional checks, like "are the light barriers are free and working?",
' but since this is not the point of this project, it is omitted due to the complexity of the implementation

if (state_doors != CLOSED) then (true)
    if (has_timer_run_out) then (true)
        :Emit cmd_doors_close;
    else (false)
        :Do nothing;
    endif
else (false)
:Do nothing;

endif

stop

@enduml