@startuml fallback_door_release_supervisor_activity

start

:Receive EV_FALLBACK_DOOR_RELEASE_BUTTON_PRESSED;


if (state_fallback_door_release == ACTIVE) then (true)
    :Emit cmd_fallback_door_release_deactivate;


else (false)

    if (state_vehicle_movement == STOPPED
        && state_vehicle_movement_info == VALID) then (true) 
        :Emit cmd_fallback_door_release_activate;
    else (false)
        :Reject request;
        :Warn driver;

    endif

endif


stop

@enduml