#ifndef SYSTEM_STATE_TYPES_H
#define SYSTEM_STATE_TYPES_H

typedef enum {
	STATE_DOOR_OPENING_PERMISSION_GRANTED,
	STATE_DOOR_OPENING_PERMISSION_REVOKED
} StateDoorOpeningPermission_t;


typedef enum {
	STATE_VEHICLE_MOVEMENT_STOPPED,
	STATE_VEHICLE_MOVEMENT_MOVING
} StateVehicleMovement_t;

typedef enum {
	STATE_VEHICLE_MOVEMENT_INFO_VALID,
	STATE_VEHICLE_MOVEMENT_INFO_TIMED_OUT
} StateVehicleMovementInfo_t;

#endif
