#ifndef SYSTEM_STATE_TYPES_H
#define SYSTEM_STATE_TYPES_H

typedef enum {
	STATE_DOOR_OPENING_PERMISSION_GRANTED,
	STATE_DOOR_OPENING_PERMISSION_REVOKED
} StateDoorOpeningPermission_t;


typedef enum {
	STATE_VEHICLE_MOVEMENT_STOPPED,
	STATE_VEHICLE_MOVEMENT_MOVING
} StateVehicleMovement_t;

typedef enum {
	STATE_VEHICLE_MOVEMENT_INFO_VALID,
	STATE_VEHICLE_MOVEMENT_INFO_INVALID
} StateVehicleMovementInfo_t;


typedef enum {
	STATE_STATION_DETECTION_DETECTED,
	STATE_STATION_DETECTION_UNDETECTED
} StateStationDetection_t;

typedef enum {
	STATE_STATION_DETECTION_INFO_VALID,
	STATE_STATION_DETECTION_INFO_INVALID
} StateStationDetectionInfo_t;

#endif
