@startuml traction_controller_fsm

state TRACTION_CONTROLLER_FSM {
    state STATE_TRACTION_CONTROLLER_IDLE
    state STATE_TRACTION_CONTROLLER_TRACTION
    state STATE_TRACTION_CONTROLLER_BRAKE
    state STATE_TRACTION_CONTROLLER_EMERGENCY_BRAKE
}

@enduml