@startuml vehicle_movement_fsm

state VEHICLE_MOVEMENT_FSM {
    [*] --> STATE_VEHICLE_STOPPED
    state STATE_VEHICLE_STOPPED
    state STATE_VEHICLE_MOVING {
        /'
        [*] --> Accelerating
        state Accelerating
        state Rolling
        state Braking

        Accelerating: traction command applied

        Rolling: traction command idle

        Braking: brake command applied


        Accelerating --> Rolling
        Rolling --> Accelerating
        Rolling --> Braking
        Braking --> Rolling
        '/
    }
}

@enduml