@startuml door_fsm
state DOOR_FSM {
    [*] --> STATE_DOORS_CLOSED
    state STATE_DOORS_CLOSED
    /'state Doors_Closing_State'/
    state STATE_DOORS_OPEN
    /'state Doors_Opening_State'/

    STATE_DOORS_CLOSED: state output: state_doors = STATE_DOORS_CLOSED

    STATE_DOORS_OPEN: state output: state_doors = STATE_DOORS_OPEN

    STATE_DOORS_CLOSED --> STATE_DOORS_OPEN : CMD_DOORS_OPEN
    STATE_DOORS_OPEN --> STATE_DOORS_CLOSED : CMD_DOORS_CLOSE
}


@enduml