@startuml stop_request_fsm




state STOP_REQUEST_FSM {
    [*] --> STATE_STOP_REQUEST_RESET
    state STATE_STOP_REQUEST_RESET
    state STATE_STOP_REQUEST_SET

    STATE_STOP_REQUEST_RESET: output state_stop_request = STATE_STOP_REQUEST_RESET 
    STATE_STOP_REQUEST_RESET: signal light off

    STATE_STOP_REQUEST_SET: output state_stop_request = STATE_STOP_REQUEST_SET
    STATE_STOP_REQUEST_SET: signal light on


    STATE_STOP_REQUEST_RESET --> STATE_STOP_REQUEST_SET : cmd_stop_request_set
    STATE_STOP_REQUEST_SET --> STATE_STOP_REQUEST_RESET : cmd_stop_request_reset
}


@enduml